---

- name: CONSUL BAREMETAL USERS | Create group
  group:
    name: "{{ consul_group }}"
    state: present

- name: CONSUL BAREMETAL USERS | Create user
  user:
    home: "{{ consul_home_dir }}"
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    system: "yes"
